### ISSUE TITLE
Test Suite could use more coverage

### ISSUE THREAD

**Issue by bendjukastein** [dangmai/prettier-plugin-apex#1077]
Howdy!

The Prettier repo could improve weaknesses in its test case by fixing a few common oversights in their test suite. I used Stryker mutation testing to evaluate your test suite, and noticed the following properties were not getting caught  by your existing tests:

1. Conditionals only being tested by the branch with more interesting behaviour, i.e. only when true or only when false:
![image](https://github.com/dangmai/prettier-plugin-apex/assets/43505516/98c00b09-8b39-4226-bec3-9693381ebd0a)
E.g. A mutant surviving that replaced the conditional with true shows a need for a new test that checks expected behaviour when the if statement evaluates to false.

2. Not checking whether strings are empty:
![image](https://github.com/dangmai/prettier-plugin-apex/assets/43505516/77eb02bc-6b54-47c7-a322-8930a644ab83)
The printer.ts test suite isn’t checking for any of these replacements in its escapeString function; a sign that new tests should be added to confirm its replacements act as expected.

Here's a summary of the overall mutation testing:
![image](https://github.com/dangmai/prettier-plugin-apex/assets/43505516/a7c3f732-a2e7-4d95-8db0-f358775f373e)
It would be good to add testing for http-server.ts 

Hope this helps make Prettier the best it can be! :)

**Comment by dangmai** [comment]
Hi, thanks for opening the issue. Code coverage for this project is run on every commit, and you can see the details for that here: https://app.codecov.io/gh/dangmai/prettier-plugin-apex and drill down to every file.
It's not my intention to cover 100% of the branches/codes, some branches are not worth it for me to test, maybe because they can never be reached (but are only there to appease the Typescript compiler), or that it'd purely be testing a 3rd party lib.
With that said, if you want to open PRs that fix some of those files, I'd happily merge them.
