### ISSUE TITLE
Support macOS x86 in native executables

### ISSUE THREAD

**Issue by kang8** [dangmai/prettier-plugin-apex#1470]
### Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java >= 11? If No, you need to install a newer Java version.
- [X] Are you running VSCode and recently upgraded Prettier or Prettier Apex? If Yes, have you restarted VSCode after the upgrade?

### Describe your issue

I am using an Apple computer that does not have an M chip, it is a macOS with x86. I hope I can use the native executables feature.

If adding support for macOS x86 means adding it to [the strategy.matrix.os in the build-native-executables job of the tests-deployments workflow](https://github.com/dangmai/prettier-plugin-apex/blob/ca4504c4838d77e562ef18f544105ead8daa361b/.github/workflows/tests-deployments.yml#L159-L177), I would be happy to submit a PR.

### System Info

```shell
System:
    OS: macOS 13.6.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 143.90 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.1 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.12.3 - /usr/local/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
```

**Comment by dangmai** [comment]
Hi there, thank you for opening the issue!

So I did debate whether to include OS X x64 or not, and unfortunately ended up deciding not to support that architecture. It's much more difficult to remove support for something than to add support for something, because removing a feature most likely breaks someone's workflow. Mac Intel is basically EOLed at this point, so if I add it now I'll have to deprecate it soon in the future, whether because I don't want to support it anymore or because some dependency involved the build process stops supporting it (i.e. GraalVM or Github Actions).

That plus the fact that I don't have a x86 Mac machine to test the executable with, makes me decide not to support that architecture.

In the future I may add the ability to build the executable yourself as part of installing this library, but that will be lower priority than adding support for emerging architectures like Windows ARM64 and Linux ARM64.

**Comment by dangmai** [comment]
I've changed my mind on this - please upgrade to Prettier Apex v2.2.0. macOS x64 is now supported for native parsing by default. Let me know if it works for you!

**Comment by kang8** [comment]
I've tested macOS x64 and can confirm that it's now over 10 times faster than before.

Thank you @dangmai
