### ISSUE TITLE
Every inner line of multi-line (block) comments should start with *

### ISSUE THREAD

**Issue by ChuckJonas** [dangmai/prettier-plugin-apex#150]
```sh
# Prettier options (if any):
```

**Input:**

```apex
/**
 * First ApexDoc
  Description
 */
```

**Actual output:**

```apex
/**
 * First ApexDoc
  Description
 */
```

**Expected output:**

```apex
/**
 * First ApexDoc
 *  Description
 */
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu] OS X
- Version: [e.g. 1.0.0] 1.1.0

**Comment by dangmai** [comment]
Thank you for the suggestion! I'm mulling this over right now, I don't think upstream Prettier does this, nor other Prettier plugins. It's certainly great for ApexDoc. I'm away from home for the holiday so it might be a few days before I get to this.

Happy turkey day meanwhile! :)

**Comment by dangmai** [comment]
Hi again, sorry for taking a while about this, I've thought about it and I can't come up with a use case that would not benefit from this, so feel free to work on your PR. However, to be on the safe side, I'd suggest only transforming the comment if it explicitly follows Javadoc convention (`/** */`), instead of all block comments (`/* */`).

**Comment by dangmai** [comment]
Closing this for now, if anyone else thinks this is desirable feel free to reopen and comment on this issue.
