### ISSUE TITLE
field_access node has extra empty space

### ISSUE THREAD

**Issue by xixiaofinland** [dangmai/prettier-plugin-apex#1633]
### Initial Apex code

```apex
public class Me {
  void dottedExprMethod() {
    a. Field__c = null;
  }
}
```

### Formatted Apex code

```apex
public class Me {
  void dottedExprMethod() {
    a. Field__c = null;
  }
}
```

### Expected Apex code

```apex
public class Me {
  void dottedExprMethod() {
    a.Field__c = null;
  }
}
```

### Playground link

https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKED7O2UIABELybIi1ALL0tcAAOvC1tQBuYBa1vDJQ9LwAooxSbVZgvAAUAJQd3b29NOy1yfTyvAD6+3UAvLXwPvLyANxrtUXdRSBFQA

**Comment by dangmai** [comment]
Thanks for opening the issue, this is a good catch. I'll fix it soon 😄

**Comment by dangmai** [comment]
This was a fun one to chase down, but unfortunately it's not something I can fix. It's a bug from `jorje`.

It parses the `a. ` as a type, i.e it sees it as analogous to something like `System.URL Field = null;`

If they fix it in `jorje`, it'll automatically be fixed in Prettier Apex as well. From the POV of this library, we have to rely on the AST provided to us by the parser, even if it's incorrect.

Closing this since it's not actionable from my side 😞

**Comment by xixiaofinland** [comment]
Quite a while ago, I made a bash script to check the hash sum of jorje.jar and automatically download the new version.
Only one week ago the hash sum altered... I even wonder if it was a false positive one 😸 

Nonetheless, thanks for checking @dangmai

**Comment by dangmai** [comment]
Yeah here's my version https://github.com/dangmai/prettier-plugin-apex/blob/master/packages/apex-ast-serializer/tools/create-jorje-jar.sh
It's run everyday to get the latest jorje version. There have been semi frequent releases every month or so
