### ISSUE TITLE
SOQL line wrapping logic

### ISSUE THREAD

**Issue by xixiaofinland** [dangmai/prettier-plugin-apex#1653]
### Initial Apex code

```apex
public class Me {
  {
    List<Account> accs = [SELECT Id FROM 
Account];
  }
}
```

### Formatted Apex code

```apex
public class Me {
  {
    List<Account> accs = [
      SELECT Id
      FROM Account
    ];
  }
}
```

### Expected Apex code

```apex
public class Me {
  {
    List<Account> accs = [SELECT Id FROM Account];
  }
}
```

### Playground link

https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKED7O2UIABELybIi1ALL0tcAAOvC1Hd29vQAyMJQAPACCQiI+JgB8tTRTzQC8tQDaAMoAooNbAML+tTG8tYkASgDyLbWT0yYAugDc-bVF3UUgRUA

**Comment by xixiaofinland** [comment]
Description:

I expected SOQL query which doesn't make the line exceeding print_width will automatically format into single line mode.
It seems when the SOQL is manually split into multiple lines, it triggers the mupti-line mode regardless.

I understand that line wrapping is probably all handled by upstream prettier so you don't have any control. Just noticed this and submit here.

**Comment by dangmai** [comment]
This is a conscious decision - you can see the user request here: https://github.com/dangmai/prettier-plugin-apex/issues/511 Sometimes I do take heuristics of the user's code into account, this is one of those situations. The reasoning here is that if a user has consciously decided to add a newline when typing out the code, I will respect that. I'm planning to add more heuristics in the future as well, in order to reduce the amount of "jank" that a user runs into inside the IDE.

I think you misunderstand the responsibility/ability of a Prettier plugin - I have full control over line wrapping behavior, the only thing Prettier core does is give me some helper primitives that make it easier to take advantage of the prettier algorithm (notice that the algorithm is _not_ the same as Prettier the library).

**Comment by xixiaofinland** [comment]
A very interesting point, and thanks for coaching me again on how Prettier Apex functions.
