### ISSUE TITLE
Unprinted Comments Error on Code Blocks

### ISSUE THREAD

**Issue by mnunezdm** [dangmai/prettier-plugin-apex#17]
Hi!

Congratulations on your repo!

I have found one issue regarding code blocks

I noticed that code blocks at the start of a trigger produce some errors, like for example an ApexDoc:

``` java
/**
* @author Salesforce.com Foundation
* @date 2014
*
* @group Accounts
* @group-content ../../ApexDocContent/Accounts.htm
*
* @description Trigger Handler on Accounts that handles ensuring the correct system flags are set on
* our special accounts (Household, One-to-One), and also detects changes on Household Account that requires
* name updating.
*/
trigger Case_trg on Case(before update) {
  System.debug('SOMETHING');
  /**else
{
Trigger.new[0].addError('some error');
}**/
}
```

That same code without the ApexDoc produces no error
 
But with strange output as the code is not following the upper indentation

```java
trigger Case_trg on Case(
  before update) {
  System.debug('SOMETHING');
  /**else
{
Trigger.new[0].addError('some error');
}**/
}
```

I have tried to guess the root cause of this issue and I have detected that when the block comment is not before the first line of code in the first code block it not fails

```java
trigger Case_trg on Case(
  before update) {
  System.debug('SOMETHING');
  /**
   **/
  System.debug('SOMETHING2');
  /**
  else
  {
  Trigger.new[0].addError('some error');
  }
  **/
}

```

If you start with a correct indentation in the comment the result is, as I would consider, correct

```java
trigger Case_trg on Case(
  before update) {
  System.debug('SOMETHING');
  /**
  else
  {
  Trigger.new[0].addError('some error');
  }**/
}
```

Also, the allineation on trigger scopes seems a little bit weird, as now is done in the same level as the first line of the code block

### System Information

+ **prettier** = 1.16.4
+ **prettier-plugin-apex** = 1.0.0-alpha.6
+ **SO** = Windows 10

**Comment by dangmai** [comment]
Thank you for your bug report, and yes the formatted code block doesn't look right. I'll take a look at this in a few days and see what I can do :) In general comments are still under active development right now, they are really hard to get right, so I appreciate all weird edge cases like this one.

**Comment by dangmai** [comment]
If I understand correctly, your report contains 2 different issues:

- The comments before the trigger declaration are not being printed, and an error is thrown:

This issue has been fixed in the `master` branch and will be in the next alpha version (alpha.8). Feel free to watch this repository releases to get notified when it's published.

- The content of the comments are not being formatted:

This is actually the desired behavior. Block comments can contain anything, and I don't think trying to format it as a good idea (even just to insert indentations).

The exception to this is if the block comment is ApexDoc, which *does* get formatted, because I already know what the ApexDoc format should look like.

if you disagree with this behavior, feel free to open another bug report for it and I'll ask the community what they would prefer.

Thank you again for the bug report, I really appreciate it!
