### ISSUE TITLE
Consistent casing

### ISSUE THREAD

**Issue by ntotten** [dangmai/prettier-plugin-apex#2]
What are your thoughts on enforcing consistent casing? I think particularly with keywords they should be always written as lowercase. Ideally, there would be an option to force other things to consistent casing as well such as class names.

**Comment by dangmai** [comment]
Yes keeping keywords case consistency would be very nice and on my todo list before the first general release for this project. Right now a lot of the keywords are already consistent, provided that they are represented by a unique node in the AST (i.e. if I print out a hardcoded string, it'll generally be consistent). However, if the AST puts them in a generic `names` node, I'm printing whatever the user puts in, for example `List<list<List<String>>>`.

One thing that I'd like to get discussion on is SOQL and SOSL - right now I have the keywords for those syntaxes UPPERCASE, since that's how they are written in all the Salesforce documentations. I don't mind it going either way, but I think it'd be nice to have consistency in documentation vs actual code.

I don't think this project is the right tool for class names/variable name consistency. To me those are better suited for linters/analyzers like PMD. Also, I generally try to follow the Prettier principal that it's [not a code transformer](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about), except for edge cases without alternatives (e.g. comments, empty trailing lines).

**Comment by ntotten** [comment]
Fair point on class/variable names. I think you’re right to keep this constrained to the core philosophy of prettier.

I agree that SOQL keywords probably make sense as upper case. I think almost everyone writes it that way.

**Comment by muenzpraeger** [comment]
+1 for SOQL/SOSL keywords

**Comment by Szandor72** [comment]
+1 for uppercase SOQL/SOSL

How about sObject field names, i.e. spell exactly as API Name? 

Having field references match the configured API Name would hopefully help memorise exact spelling for use in Lightning. Just a thought.

**Comment by dangmai** [comment]
Hi @Szandor72, that's a good idea - unfortunately I don't get the "correct" API Names from the parser that Salesforce provides (it only gives me exactly what you have in your code), and implementing that would bring the scope of this project larger than I'd like.

**Comment by dangmai** [comment]
Thanks for the discussion everyone, here's what I'm going for:

- Non SOQL/SOSL keywords on this list (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reserved_words.htm) will be lowercased.
- SOQL/SOSL keywords will be UPPERCASED.

I'll close this ticket for now. If you find that there are inconsistent casing in your formatted code (I know there are, since I haven't had time to replace all instances of the keywords in the code yet), please open a bug report and I'll fix it individually.
