### ISSUE TITLE
`--apex-standalone-parser built-in`  should have a fallback instead of crashing

### ISSUE THREAD

**Issue by aheber** [dangmai/prettier-plugin-apex#204]
Using `--apex-standalone-parser built-in` but not having the local server running results in formatting failure. Would be nice if it fell back to spinning up the AST generation on its own instead of exploding.

We are going to take effort to get machines setup to run the server locally but can't guarantee it will always be available in every case. e.g. VS Code is not running but we run `prettier` during Git hook. If VS Code is the automatic local server startup and that isn't happening because VS Code isn't open, the Git hook will fail rather than just being slow.

**Actual output:**

```
[error] path\to\code\code.cls: TypeError: Cannot read property 'unit' of undefined
[error]     at FastPath.call (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:12771:18)
[error]     at genericPrint (C:\Users\aheber\dev\SFDC\node_modules\prettier-plugin-apex\src\printer.js:2800:20)
[error]     at Object.printGenerically [as print] (C:\Users\aheber\dev\SFDC\node_modules\prettier-plugin-apex\src\printer.js:2833:15)
[error]     at callPluginPrintFunction (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:12988:18)
[error]     at printGenerically (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:12934:13)
[error]     at printAstToDoc (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:12950:13)
[error]     at coreFormat (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:13271:13)
[error]     at format (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:13516:73)
[error]     at formatWithCursor (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:13532:12)
[error]     at Object.formatWithCursor (C:\Users\aheber\dev\SFDC\node_modules\prettier\bin-prettier.js:44213:15)
```

**Expected output:**
Formatting should succeed even if server was expected but unavailable

**Additional information (please fill this out)**:

- OS: Windows
- Version: 10

**Comment by aheber** [comment]
If this can be done with minimal effort and performance impact, maybe the built-in server can be auto-detected (respecting prettier config for address and port) instead of declared?

**Comment by dangmai** [comment]
Hi, thank you for opening the issue. Unfortunately I don't think I agree with the approach of automatically falling back. Generally I subscribe to the philosophy of explicit over implicit, and in this case I'd much rather the tool failing instead of running slower. One example I can think of is if a team runs this tool as part of their CI/CD pipeline and pays by the minute (it's a pretty common scenario) - if the server somehow fails after an update and the tool keeps running at much slower speed, then suddenly you have to pay about 5-10 times more without any warning.

One way you can handle this situation is by using other tooling, for example in Unix-based systems you can follow something like [this](https://stackoverflow.com/questions/11904772/how-to-create-a-loop-in-bash-that-is-waiting-for-a-webserver-to-respond).

One thing I do want to improve is the messaging when Prettier fails to reach the built in server, currently it's very non-descriptive. Maybe I can exit the process with a particular status code in that case - and you can check for it and spins up Prettier Apex without the external parser.

**Comment by dangmai** [comment]
I'm closing this ticket because I don't think it's the path I want to go down, but feel free to add more discussions here! If other people feel like they prefer the approach in the OP, please comment here as well.

**Comment by aheber** [comment]
Possible to have a comma-separated list so people can opt-in? I understand the feeling of not wanting to fallback to what might be an expensive option "by surprise" but what are you feelings of allowing users to control that behavior with declared options?

I expect the right option here for now might be to have a script on the Git Hook, that script looks for the server and starts it if needed, runs prettier on all the committed files, then shuts down the server if it was the one that started it.

**Comment by sjurgis** [comment]
I've just had the same error in our CI build. The way we run it is:

> start-apex-server & sleep 10s && prettier --write 'decsond/**/*.{trigger,cls}' --tab-width 4 --print-width 100 --apex-standalone-parser built-in && stop-apex-server

**Comment by dangmai** [comment]
You can do this:

```
start-apex-server && npx wait-on http://localhost:2117/api/ast/ && prettier --write 'decsond/**/*.{trigger,cls}' --tab-width 4 --print-width 100 --apex-standalone-parser built-in && stop-apex-server
```

It will wait for the HTTP server to be up before running Prettier, no matter how long that takes :)

I'll probably add that to the README soon. Thank you for the suggestion!

**Comment by sjurgis** [comment]
It should be single ampersand after `start-apex-server`, like this:
`start-apex-server & npx wait-on http://localhost:2117/api/ast/ && prettier --write 'decsond/**/*.{trigger,cls}' --tab-width 4 --print-width 100 --apex-standalone-parser built-in && stop-apex-server`

**Comment by dangmai** [comment]
Yup that's my bad, in my project I also use `nohup` as well before `start-apex-server &`. Thanks for pointing it out!
