### ISSUE TITLE
NULL and TRUE/FALSE in SOQL gets translated to lowercase

### ISSUE THREAD

**Issue by sjurgis** [dangmai/prettier-plugin-apex#209]
**Input:**

```apex
class foo {
  Account[] foo = [SELECT Id FROM Account WHERE Id != NULL];
  Lead[] foo = [SELECT Id FROM Lead WHERE IsConverted = TRUE];
}
```

**Actual output:**

```apex
class foo {
  Account[] foo = [SELECT Id FROM Account WHERE Id != null];
  Lead[] foo = [SELECT Id FROM Lead WHERE IsConverted = true];
}

```

**Expected output:**

```apex
class foo {
  Account[] foo = [SELECT Id FROM Account WHERE Id != NULL];
  Lead[] foo = [SELECT Id FROM Lead WHERE IsConverted = TRUE];
}
```

**Additional information (please fill this out)**:
```
    "prettier": "^2.0.5",
    "prettier-plugin-apex": "^1.3.0"
     Catalina 10.15.4 (19E266)
```

Looking at SOQL spec [Booleans](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_filtering_on_booleans.htm) are uppercase and [null](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_null.htm) is [inconsistent.](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_alias.htm?search_text=null)

I can't find any setting of documentation on this feature - neither in prettier project neither in this project.

**Comment by dangmai** [comment]
Hi, thank you for the issue.

I don't believe there's actually any spec on which keywords are capitalized or not capitalized, even the docs you link to are very inconsistent when it comes to capitalization, here are a few examples:

- https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_agg_functions.htm?search_text=false (look at the SUM() example).
- https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_comparisonoperators.htm?search_text=false (the Multiple Semi-Joins or Anti-Joins example).

These are all just conventions that differ between different teams. Moving everything to lower case makes it consistent with other parts of Apex (for example `true`, `false`, and `null` are all lower cased in non-SOQL Apex code). At this point, I don't foresee changing that because that'd require a major version bump for this project, and I'm not convinced the pros outweigh the cons.

I'm going to close this ticket, but feel free to add more discussions here. If other people feel UPPERCASE is more appropriate, I'm open to change the decision later on.

**Comment by sjurgis** [comment]
Formatter that's been before apex-prettier (Illuminated Cloud) does uppercase.
SOQL keywords are obviously meant to be uppercase, it has nothing to do with apex.

**Comment by SCWells72** [comment]
I'll provide some context. At least in Illuminated Cloud, I followed the patterns established by the respective base languages. Apex syntax is heavily indebted to Java (in particular Java 5), and SOQL is influenced by both SQL and object-oriented query languages like JPQL and HQL.

In Java the literal keywords (`null`, `true`, `false`) are, like all other keywords, lower-cased, so Illuminated Cloud's Apex code completion engine and case verification code inspection drive the corresponding literal keywords toward lower-cased.

For the most part the query languages are case-sensitive, but the most common convention for keywords is upper-cased. As a result, Illuminated Cloud's SOQL/SOSL code completion engine and case verification code inspection drive the corresponding literal keywords toward upper-cased.

I don't really have a stake in this, but I was asked to provide the background and motivation for how Apex is influenced by Java and SOQL is influenced by SQL/JPQL/HQL respectively in terms of keyword casing rather than a least common denominator approach due to the ability to embed the latter in the former.

**Comment by dangmai** [comment]
Thanks for chiming in Scott, I appreciate it. I actually do think that uppercase keywords make sense in SOQL, which is why I format almost all of them (SELECT, FROM, WHERE, etc.) that way.

However, because of the way Prettier works (there's only one output possible for an AST), anything that I change after a major version (in this case, 1.0) has a major impact on all the code bases that depend on this library - because if they run lint check as part of the CI/CD pipeline, a different decision in later versions will cause their CI/CD pipelines to break. I try to minimize this as much as possible, especially for something as primitive as true/false/null.

The decision is not based on my preference (I do prefer uppercase keywords for SOQL, the lowercased null/false/true were made at the very start of this project among a thousand other decisions), but based on the fact that I want to minimize impact now that this has been widely adopted (based on the number of packages that depend on it). Hence why I said I'm open to changing my mind if enough people chime in and say it's a pain point for them.

Hope this clears things up. I appreciate your inputs! 👍

**Comment by SCWells72** [comment]
Sure, no problem. Like I said, I don't really have a stake in this...well, that's not entirely true because I do have users on teams who are hybrid Illuminated Cloud / VS Code extensions who would like to have a common code style across tools, and this disparity makes that more difficult...but more than anything I just wanted to share the motivating thoughts on IC's approach to this same problem.

I haven't looked at Prettier, but assuming you have access to an AST I'm surprised that there's not a way to have a formatting rule have conditional behavior based on, for example, whether the current node is within an embedded query or not. Is that not the case? I guess I could take a look myself when I have a chance...

Anyway, let me know if there's any other info I can provide. I'm happy to do so.

**Comment by dangmai** [comment]
Hey Scott, it's actually really easy to make this change, the nodes have different JVM types in SOQL vs Apex. It's not really a technical issue, it's more of a change management issue - I try to minimize "core" formatting decisions as much as reasonable after the first major version, because of how many potential users I might affect. Something like this would require a major version bump, and for that I'd like to hear from more people that it's a pain point for them.

I do see where you're coming from though, I'll definitely keep the context of users using both IC and Prettier in mind.

**Comment by dangmai** [comment]
The number of people who told me they prefer uppercase TRUE, FALSE, NULL have reached the critical mass  for me to change the behavior of Prettier Apex. I've put in a fix for this in `master`, and the next version will include it.

Thank you everyone for chiming in!
