### ISSUE TITLE
Multiline addition doesn't indent as expected.

### ISSUE THREAD

**Issue by boxfoot** [dangmai/prettier-plugin-apex#21]
When a binary expression (like addition) breaks across lines, the subsequent lines don't indent as expected.

Expected output (can also use as input):

```java
class PrettierTests {

	public void multilineAddition() {
		String myString = 'a long string ' +
			'from concatenating ' +
			'many other strings ' +
			'together.';
	}

}
```

Actual output:

```java
class PrettierTests {
	public void multilineAddition() {
		String myString = 'a long string ' + 'from concatenating ' +
		'many other strings ' +
		'together.';
	}
}
```

As an aside, I would personally prefer if the line breaks were before the operator rather than after, but I understand that [prettier isn't going that direction](https://github.com/prettier/prettier/issues/3806) and apex-prettier should probably follow them... but if there's openness to adding that as an option I think it would add a lot of value.

**Comment by dangmai** [comment]
Thank you for the bug report! I am actually in the process of fixing this right now - it's a bit more complicated than other indentation issue because of the way `jorje` (the Salesforce parser/compiler) constructs the Abstract Syntax Tree. I agree with the sample Expected Input that you have.

I do see the pros in putting line breaks before the operator - namely, if we need to add more stuffs to the expression later on, the diff will only touch the new lines and not the old ones. That said though, I would prefer to keep the formatting for this library close to Prettier's choice, because there's a good chance that people will use Prettier for both Apex and Javascript (w/ Aura or LWC) and it makes sense for everything to look similar-ish.

**Comment by boxfoot** [comment]
@dangmai amazing!  Thanks.  I'm so excited about apex-prettier and it's mostly working in our huge codebase.   Just submitting issues for a few of the bugs we noticed as we implemented this week.

I agree w/ staying close to prettier here, I'm just frustrated and confused as why they're refusing to implement an option for something which is objectively clearer and more readable code (as discussed in that issue), makes clearer diffs, and so many people are asking for.  (And part of my wonders if enough prettier plugins implemented an option for this with consistent syntax, would core be willing to follow...)

**Comment by dangmai** [comment]
That's great to hear! I'd welcome bug reports of any type, since I've mostly ran this on open source Apex projects and my company's own project, and that might not cover the entire functionality for Apex. Salesforce doesn't publish comprehensive documentation for Apex either, so sometimes it's plain old reverse engineering and there might be things that I've missed :) 

I do understand your frustration with core's decision. If they decide to change it in the future I'll be more than happy to go that route with this library as well.

**Comment by dangmai** [comment]
I finally managed to fix this, it turned out to be a much much more difficult issue to tackle than I originally thought.
The fix will be included in the next release. There will be a lot of formatting changes in it.

Thanks again for the bug report!

**Comment by boxfoot** [comment]
Thanks so much!   This looks great.
