### ISSUE TITLE
Queries in a Ternary

### ISSUE THREAD

**Issue by kacrouse** [dangmai/prettier-plugin-apex#223]
```sh
# Prettier options (if any):
--tabwidth 4
```

**Input:**
```apex
List<Account> accounts = true ? [SELECT Id FROM Account WHERE Name = 'a name' OR Name = 'another name' OR Name = 'one more name'] : [SELECT Id FROM Account WHERE Name = 'a name' OR Name = 'another name' OR Name = 'one more name'];
```

**Actual output:**

```apex
List<Account> accounts = true
    ? [
            SELECT Id
            FROM Account
            WHERE
                Name = 'a name'
                OR Name = 'another name'
                OR Name = 'one more name'
        ]
    : [
            SELECT Id
            FROM Account
            WHERE
                Name = 'a name'
                OR Name = 'another name'
                OR Name = 'one more name'
        ];
```

**Expected output:**

```apex
List<Account> accounts = true
    ? [
        SELECT Id
        FROM Account
        WHERE
            Name = 'a name'
            OR Name = 'another name'
            OR Name = 'one more name'
    ] 
    : [
        SELECT Id
        FROM Account
        WHERE
            Name = 'a name'
            OR Name = 'another name'
            OR Name = 'one more name'
    ];
```

**Additional information (please fill this out)**:
This one's a bit elusive because if tab width is set to 2, the query looks good because everything coincidentally lines up. Things start look a bit strange once tab width increases.

- OS: Windows
- Version: 1.5.0

**Comment by dangmai** [comment]
Hey, thanks for the bug report 🚀!  This is definitely an interesting case and I have to look deeper into it. From a comment I made awhile ago https://github.com/dangmai/prettier-plugin-apex/blob/834c0984d7eb68a8e84265cc0a938a6ff8747bbc/src/printer.js#L1462 I think those were by design - but maybe what I can do is to make an exception for SOQL queries, because your expected output does look better to me. I'll have to check whether adding that in would break anything else instead.

**Comment by kacrouse** [comment]
Ah, that's interesting! Yeah, I agree with the comment and what you're saying. The double indent makes sense for method chaining, but I think there may be a few other cases besides queries where it doesn't make sense. The two I can think of are list initialization (`new List<Object> {...}`) and long parameter lists (`method(a,b,c,d,e,f,g,...)`). I'm wondering if method chaining might actually be the exception and the standard path should just be a single indent?

**Comment by dangmai** [comment]
That's a really good point, that's probably where I'll end up going :)

**Comment by dangmai** [comment]
Just an fyi that I haven't forgotten about  this ticket. The issue I'm running into right now is that it's more difficult than I anticipated initially - your expected output would look good for tabwidth 4, however for tabwidth 2 it would look like this:

```
List<Account> accounts = true
  ? [
    SELECT Id
    FROM Account
    WHERE
      Name = 'a name'
      OR Name = 'another name'
      OR Name = 'one more name'
  ] 
  : [
    SELECT Id
    FROM Account
    WHERE
      Name = 'a name'
      OR Name = 'another name'
      OR Name = 'one more name'
  ];
```
By default, tabwidth is 2 so the default behavior would look "off".

One possible thing I could do is mark the opening `[` as a "root", and indent based on that root. It means that for tabwidth 4, it would look like this:

```
List<Account> accounts = true
    ? [
          SELECT Id
          FROM Account
          WHERE
              Name = 'a name'
              OR Name = 'another name'
              OR Name = 'one more name'
    ] 
    : [
          SELECT Id
          FROM Account
          WHERE
              Name = 'a name'
              OR Name = 'another name'
              OR Name = 'one more name'
    ];
```

And for tabwidth 2, it looks like this:

```
List<Account> accounts = true
  ? [
      SELECT Id
      FROM Account
      WHERE
        Name = 'a name'
        OR Name = 'another name'
        OR Name = 'one more name'
  ] 
  : [
      SELECT Id
      FROM Account
      WHERE
        Name = 'a name'
        OR Name = 'another name'
        OR Name = 'one more name'
  ];
```

The issue with that approach is that if the user chooses to use tabs instead of spaces (i.e. `useTabs: true` in their `prettierrc`), they will see a mix of tabs and spaces in their output, because we're using spaces for alignments and tabs for indentations.

I think this is one of the edge cases in which I can't handle every situation perfectly - I just need to commit to _some_ approach that will look "off" to the least amount of people.

**Comment by dangmai** [comment]
Another approach might be this, for tabwidth 4:

```
List<Account> accounts = true
    ?
        [
            SELECT Id
            FROM Account
            WHERE
                Name = 'a name'
                OR Name = 'another name'
                OR Name = 'one more name'
        ]
    :
        [
            SELECT Id
            FROM Account
            WHERE
                Name = 'a name'
                OR Name = 'another name'
                OR Name = 'one more name'
        ];
```

That's the "logical" way to format the output and maintain consistency, but obviously it takes up a lot of spaces. Upside is that it will work regardless of spaces/tabs/tabwidth.

**Comment by kacrouse** [comment]
Just did a little research because we're definitely not the only ones trying to figure this out 😄 

[Here's an alternative way of formatting](https://github.com/prettier/prettier/issues/5814#issuecomment-468829133), which looks fairly clean and I _think_ wouldn't require any special handling... and it seems to handle nested ternaries as well.

Applied to our example:
```
List<Account> accounts = true ? [
    SELECT Id
    FROM Account
    WHERE
        Name = 'a name'
        OR Name = 'another name'
        OR Name = 'one more name'
] : [
    SELECT Id
    FROM Account
    WHERE
        Name = 'a name'
        OR Name = 'another name'
        OR Name = 'one more name'
];
```
It might be slightly less readable, but I think multiline ternaries are pretty hard to read no matter how you format them.

**Comment by dangmai** [comment]
Thanks for doing the research! 🔥  I'll have to read through that entire thread history to see how the core team came to their decision. I can see the appeal of that output, although I'm not sure how it will be applied to non-SOQL statements. Let me try it out and see how it looks.

**Comment by dangmai** [comment]
As you can probably see in that thread, if we go with the alternative formatting in your last post, one of the consequences would be that there's no good way to show multiple ternary nest levels. I don't really want to go there, I know Prettier core team decides to do that but it's a really big controversy for them to do so.

I'm still really torn on this currently. You also rightly pointed out that this is doesn't just affect SOQL queries but also other constructs, and it's especially noticeable when the users choose a non-standard tab width, so I don't think the current implementation is sufficient either.

Those were just some rambling thoughts, because I still don't know what to do hahaha 🙅

**Comment by dangmai** [comment]
Another thing I'm trying right now is to keep the current implementation for default tabWidth (2), but take out the additional indentation level for anything greater than that (3, 4, 5, etc.) I'm not a big fan of formatting differently based on tabWidth options (because it makes maintenance really difficult later on), but it might be the least-worst option for us.

**Comment by dangmai** [comment]
So I've made the decision to use alignment instead of indentation to provide clarity for ternary expressions, which is what I described above as marking roots. See the actual output for your example [here](https://github.com/dangmai/prettier-plugin-apex/blob/4b18f5f1abdc1ea9b622d09d68ac503573cc4dd9/tests/ternary/__snapshots__/jsfmt.spec.js.snap#L243) with `tabWidth` set to 4.

It's not exactly what you asked for originally, but I think it's very readable, and easy for me to maintain.

Now I'm waiting for people who use tabs to yell at me for mixing tabs & spaces for alignment 🤣 

Thank you for reporting this 🚀 I will be releasing a new version soon that contains this fix.
