### ISSUE TITLE
Alias Removed from SOQL query

### ISSUE THREAD

**Issue by kend77** [dangmai/prettier-plugin-apex#25]
Expected output:

```apex
class PrettierTests {
         public static User currentUser;
	public void getCurrentUser() {
	     	this.currentUser = [
			SELECT u.Name, u.Email, u.Id, u.IsPortalEnabled
			FROM User u
			WHERE u.Id = :Userinfo.getUserId()
		];
	}

}

// Actual output:

class PrettierTests {
	public static User currentUser;
	public void getCurrentUser() {
	     	this.currentUser = [
			SELECT u.Name, u.Email, u.Id, u.IsPortalEnabled
			FROM User
			WHERE u.Id = :Userinfo.getUserId()
		];
	}
}

**Comment by dangmai** [comment]
Thank you for the bug report! That's pretty serious, but luckily pretty easy to fix. I'll include the fix in the next version.

**Comment by dangmai** [comment]
This has been fixed in `master`, I will push a new version with that fix some time this week.

Let me know if you find any more issue, I really appreciate it. Salesforce doesn't provide comprehensive documentation  on Apex/SOQL/SOSL syntaxes so I have to do a lot of reverse engineer myself. This issue stems from their documentation [here](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select.htm), which suggests that aliases are not allowed after a `FROM objectType` (even though they clearly are).
