### ISSUE TITLE
Improve performance by changing built-in parser to make http requests instead of shelling out

### ISSUE THREAD

**Issue by drubin** [dangmai/prettier-plugin-apex#287]
The current implementation of `--apex-standalone-parser built-in` is to shell out to a nodejs script that makes an HTTP call to the apex language server. Shelling out is slow as it creases a subprocess a passes all env and other data to the proccess.

We could improve the performance by simply moving this code out of `http-client` https://github.com/dangmai/prettier-plugin-apex/blob/master/src/http-client.js#L5-L20  into the `parser` https://github.com/dangmai/prettier-plugin-apex/blob/master/src/parser.js#L42-L67

Is there a reason for doing this? or is this simply to maintain feature similarity with `parseTextWithSpawn`?

**Comment by dangmai** [comment]
Thank for you for the enhancement request! Unfortunately it is that way because of a technical limitation from Prettier's (the upstream project) plugin architecture.

Basically as a Prettier plugin we follow certain conventions to parse code into AST nodes and then write them out. One of the conventions is that we have to implement a synchronous `parse` method, which rules out making HTTP calls since they are also asynchronous (as far as I know). If you know of a way to make HTTP calls synchronously I'd be very glad to use them - I've been trying to find one for a while without result. Shelling out is currently the only synchronous way to handle this issue.

Here's the feature request ticket for async parser/writer for Prettier: https://github.com/prettier/prettier/issues/4459

**Comment by drubin** [comment]
Wow learn something new every day :) I suspect shelling out to curl would help. 

Or even supporting fifo sockets in the java application. This way you can write and read files. 

But it's kinda odd that they don't support async plugins yet yargs has supported it for some time already. 

Either way thanks for the quick feedback. I was trying to quickly improve performance it takes way too long on a large code base...

**Comment by dangmai** [comment]
No problem man, I totally understand that performance has a lot to be improved, and it's always one of my top priorities to squeeze out performance.

The reason Prettier doesn't support async parsing is because all of their natively supported languages have native Javascript parser, so there's no need to reach out to any external services to get the parsed AST. Prettier plugins are generally second class citizens so we just have to work with what we have, or contribute back to the upstream project for enhancements to the plugin structure. I totally understand their POV though, time is limited so they have to prioritize some things over others.
