### ISSUE TITLE
Ignoring Lines Not Working with Safe Navigation Operator

### ISSUE THREAD

**Issue by timswilson** [dangmai/prettier-plugin-apex#361]
**Input:**

```apex
      // prettier-ignore
      ID warehouseLocationId = [
        SELECT Id
        FROM Warehouse_Location__c
        WHERE Warehouse__c = :warehouseID AND Receiving_Location__c = true
        LIMIT 1
      ]?.Id;

    // Note I have also tried 
 
      // prettier-ignore
      ID warehouseLocationId = [SELECT Id FROM Warehouse_Location__c WHERE Warehouse__c = :warehouseID AND Receiving_Location__c = true LIMIT 1 ]?.Id; 

```
**Output:**

Every time I attempt to use the new Safe Navigation Operator prettier stops formatting the file. In the prettier console, I receive the following error. I thought if I added the //prettier-ignore comment the line would be ignored, but I still receive the error and the file doesn't format.

["ERROR" - 8:58:21 PM] Error formatting document.
Error: Unexpected token '.'.. Syntax(error = UnexpectedToken(loc = (49, 9, 187, 188), token = '.'))

[Here is the link to the Safe Navigation Operator documentation](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_SafeNavigationOperator.htm)

**Additional information (please fill this out)**:

- OS: [OSX]
- Version: [11.2.3]

**THANK YOU FOR THIS PLUGIN!!!**

**Comment by dangmai** [comment]
Hi, thank you for the bug report. The latest version of this plugin already supports the Safe Navigation Operator, so I highly suggest you upgrade to that version. Unfortunately support for that operator was added recently to `jorje` (Salesforce parser), so if you used an older version of this plugin your code can't even get past the parsing phase, which is why `prettier-ignore` does not work.

I can't think of another workaround for this beside upgrading the plugin, so I'm going to close this issue, but feel free to add comments here if you need help with that.

**Comment by timswilson** [comment]
Hi,

Thank you for your response. I tried to update the plugin by re-running the command to install globally. I assumed this would install/update to the newest version. The command ran successfully, but I'm experiencing the same issue. Would you mind pointing me in the right direction on how to update the plugin correctly? Thank you!

**Comment by dangmai** [comment]
Do you use this plugin in VSCode, or on its own? One thing Id try is to run this in your project directory:

```
npm install --save-dev prettier-plugin-apex@^1.9.1
```
