### ISSUE TITLE
AST verification does not succeed because of jorje's interpretation of white spaces

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#38]
As part of the upcoming public release, I added an option `--apex-verify-ast` in order for the user to check that the AST before and after the format are the same. However, because of that I've discovered that `jorje` parses certain nodes differently based on whether there were whitespaces in the source code. Here's an example:

```apex
a .Field__c
```
and
```apex
a.Field__c
```

The first example yields this node:
```
{
  "@class": "apex.jorje.data.ast.Expr$VariableExpr",
  "dottedExpr": {
    "value": {
      "@class": "apex.jorje.data.ast.Expr$VariableExpr",
      "dottedExpr": {
      },
      "names": [
        {
          "@class": "apex.jorje.data.Identifiers$LocationIdentifier",
          "value": "a",
        }
      ]
    }
  },
  "names": [
    {
      "@class": "apex.jorje.data.Identifiers$LocationIdentifier",
      "value": "Field__c",
    }
  ]
}
```

and the second one yields this:

```
{
  "@class": "apex.jorje.data.ast.Expr$VariableExpr",
  "dottedExpr": {
  },
  "names": [
    {
      "@class": "apex.jorje.data.Identifiers$LocationIdentifier",
      "value": "a"
    },
    {
      "@class": "apex.jorje.data.Identifiers$LocationIdentifier",
      "value": "Field__c",
    }
  ]
}
```

To me they should yield the same thing (I think the 1st output can apply more generally so I prefer it), but there might be some edge case that I haven't thought of. Pinging @praksb, @ntotten since I think I'll need help on the jorje side:

- First off, is my understanding correct that those two pieces of code are functionally equivalent?
- If yes, is there a flag I can turn on that would make jorje return the same thing in the 2 examples above?

I do consider the AST verification important for the first public release, because I don't want user's code behavior to change after formatting without some form of error message.

Here's a bit of context for why I need to compare these ASTs - this block of code:

```
String veryLongStringThatWillLeadToTheLineBeingBrokenUp = someVeryLongVariableName.someVeryLongPropertyName.anotherVeryLongPropertyName;
```

should be formatted to something like:

```
String veryLongStringThatWillLeadToTheLineBeingBrokenUp = someVeryLongVariableName.
  someVeryLongPropertyName.
  anotherVeryLongPropertyName;
```
By the eye test the two blocks of code are equivalent, but the ASTs produced are different so the test produces false negatives.

**Comment by dangmai** [comment]
Opened a PR for this https://github.com/dangmai/prettier-plugin-apex/pull/39 that contains a failing test for now.

**Comment by praksb** [comment]
@dangmai They should be functionally equivalent. Can you try the jar from here?: https://github.com/forcedotcom/salesforcedx-vscode/tree/fixASTdiff/packages/salesforcedx-vscode-apex/out 

This jar has the fix to generate the same AST. However, we may not end up merging this change in our main branch since there are some concerns around how this change in AST might affect future compiler stages.

**Comment by ntotten** [comment]
@praksb would it maybe be possible to have this in the official build but with a flag to turn it on?

**Comment by praksb** [comment]
I am getting some pushback checking this into the official build since the flag would be an option in the parser which is part of the Apex compiler and there are some concerns on the output AST that the parser produces with this flag turned on in case this AST ends up being used in subsequent stages of the compilation. I am following up on this but checking in to the official build might take a lot longer.

**Comment by dangmai** [comment]
@praksb I appreciate you trying to push this into the official build, even if it's getting push backs :) 

Currently I'm using a workaround for the AST verification part - whenever I see a nested Variable Expression inside a `dottedExpr`, I'm concat-ing the `names` from that node to the `names` in the `dottedExpr`, and replace the `dottedExpr` with the `dottedExpr` one level down - like so: https://github.com/dangmai/prettier-plugin-apex/blob/6c90c70526b765b60e6417917d3cd67b8fc73401/src/util.js#L65 It's working well so far in my test cases but I am not sure whether there are edge cases in the wild that will break this.

I did actually tried out your approach a couple days ago but it turned out more difficult than the approach I described above.

One downside to my workaround is that the AST is only massaged during the AST verification phase, so during the printing phase (which is earlier than the verification), the 2 nodes are still are different. This leads to differences in the output from these 2 code blocks:

```
CustomObject__c customObject = generator.objectBuilder.setExternalId(account.personContactId).getInstance();

CustomObject__c customObject = generator.objectBuilder
      .setExternalId(account.personContactId)
      .getInstance();
```
which gets formatted as:

```
CustomObject__c customObject = generator
  .objectBuilder
  .setExternalId(account.personContactId)
  .getInstance();

CustomObject__c customObject = generator.objectBuilder
  .setExternalId(account.personContactId)
  .getInstance();
```

I don't think it's that big of a deal, because it still follows Prettier core principal: one AST should lead to exactly to one output, and technically the ASTs are different for those 2 code blocks :)

I'm holding this issue open in the hope that your fix gets included in the published branch, since the example above would get "fixed" if it does.

**Comment by praksb** [comment]
@dangmai It turns out we actually produce different bytecode as well in some cases when you have space in variable expressions. This was primarily done for backwards compatibility reasons for verification purposes as we were rolling out a new compiler. We now need to verify that the bytecode change will not cause a functionality regression before we could alter the AST. We may decide to version out the old behavior as well. This means that the change in official build may take a while given other priorities for the team that works on the compiler. There are also concerns that adding a flag would just enable two different compiler behaviors which the team would like to avoid in the published build. So for now the workaround that you have would probably be the best solution.

**Comment by dangmai** [comment]
I am closing this ticket since I've found a work around for it. Obviously it will still be great if the actual fix can make it into the published version of jorje, since it will help a lot with the amount of tech debt I'm accruing for this project just to work around this issue :smile:

**Comment by dangmai** [comment]
I have to reopen this since https://github.com/dangmai/prettier-plugin-apex/issues/69 shows me that the 2 blocks of code in that bug report are not functionally equivalent.
@praksb could you let me know the cases in which spaces make a difference in the output bytecode? Without knowing that it's pretty dangerous for me to format anything that are in `names` and `dottedExpr`.

Right now it looks like static method calls cannot be safely broken up, and I do know that `super` variable expression cannot be broken up either. Are there other cases that be taken care of?

**Comment by praksb** [comment]
@dangmai This appears to be a very tricky area for the Apex compiler. There is a difference in bytecode due to legacy reasons but that should not functionally alter the behavior of the code. Having said that I don't have a good comprehensive list of all the cases here and I have also not validated it. The issue seems to be specific to members of sObjects though. 

The issue in #69 is a bug in the Apex Compiler as well (once again related to sobjects) and I have reached out to that team to see if we could have a fix in the coming weeks. The validation for the fix is also tricky since we need to make sure it doesn't break any existing customer code. 

For now until we have a fix on the Apex Compiler is it possible for you to skip formatting VariableExpr and MethodCallExpr if they contain dottedExpr?

**Comment by dangmai** [comment]
What I'm thinking is that if `names` contains multiple expressions then I won't break them up, but I should be able to break after `dottedExpr` - I've tried this method on a couple of test cases and it seems to work. 
If I stop formatting `VariableExpr` and `MethodCallExpr` altogether when they have `dottedExpr` then a lot of real world code won't get formatted. I will deal with any potential issue that comes from that on a case by case basis - hopefully there won't be too many of them.
Could you let me know if/when the Apex Compiler gets fixed and accept the output in #69 ? I'd much prefer not to take on more tech debt to handle syntactically correct Apex code that somehow gets rejected by the compiler.

Thank you!

**Comment by praksb** [comment]
@dangmai Sure. I'll update you when a fix is available.

**Comment by dangmai** [comment]
I'm closing this ticket. I think the current formatting decision is _good enough_ (TM).
