### ISSUE TITLE
Capitalise Class Names

### ISSUE THREAD

**Issue by TomSesselmann** [dangmai/prettier-plugin-apex#428]
**Input:**

```apex
map<string, list<account>> temp;
```

**Actual output:**

```apex
map<string, list<account>> temp;
```

**Expected output:**

```apex
Map<String, List<Account>> temp;
```

**Additional information (please fill this out)**:

- OS: macOS 11.6
- Version: "prettier-plugin-apex": "^1.10.0"

**Comment by brsanthu** [comment]
While it is not prettier domain to transform the code, I think this is a great feature to have with additional config (turned off by default). This could be done for all known standard classes like String, Boolean, Date, DateTime etc., Case-insensitive nature of Sfdc comes in handy in this case so even if you mess up case in some cases, it will not matter.

Thanks for looking into this.

**Comment by AndrewRayCode** [comment]
FWIW as a user of this library, I also don't think it's in prettier's domain to capitalize variable names. Among Apex's thousands of flaws, I don't think Apex's flaw of ignoring object case is not something prettier should fix. That's more in the realm of a PMD type tool.

**Comment by dangmai** [comment]
I would agree with you @AndrewRayCode here. I kept this ticket opened just to see if it's even possible to do this in a safe way, and based on all my research I don't think it's a safe operation to do anyway.

It's true that Apex is case insensitive, but that's not how _all_ Apex code is used. I can see a few  ways that changing the capitalization can break existing code:

- If the class structure is serialized in anyway. For example, if you serialize a class instance into JSON to be consumed by Javascript, you will run into trouble because Javascript is case sensitive.

- If you use other tools like PMD that parse the AST for Apex code, and your tool doesn't take care of case sensitivity, you'll also be in trouble.

Because of all these reasons, I don't think I will go ahead with this ticket.
