### ISSUE TITLE
Request: an API usable way to specify the listening ip for the standalone server.

### ISSUE THREAD

**Issue by codefriar** [dangmai/prettier-plugin-apex#476]
I'm executing prettier-apex in a web service context, and using the prettier JS api to invoke prettier-apex. Due to system constraints (heroku) I'm using the built-in http server, but I haven't found a way to set the server's listening port: it defaults to 127.0.0.1, i need it to be a given ip. Thoughts?

**Comment by dangmai** [comment]
Yes you are correct, I actually just realized that the other day as well while fixing a bug with ipv6. I'll most likely add a flag to apex-ast-serializer for it soon. As a very hacky workaround before I implement that flag, you can use something like [ngrok](https://ngrok.com/) to expose that port.

**Comment by codefriar** [comment]
Sadly In my runtime environment I can't use ngrok. I was wondering if there was a runtime flag for jetty i could use? -Djetty.ip=0.0.0.0 ? I tried IP and that's not right, but I'm not having much luck googling

**Comment by dangmai** [comment]
Generally speaking it would be `-Djetty.host` or setting the environment variable `JETTY_HOST`, however as far as I know that doesn't work because I am using jetty in embedded mode, which means everything is [configured](https://github.com/dangmai/apex-ast-serializer/blob/master/src/main/java/net/dangmai/serializer/server/HttpServer.java#L31) programmatically.

Funnily enough on my machine Jetty defaults to listen on `0.0.0.0` instead of just `127.0.0.1`, I wonder if it's because of difference in JVM. Could you paste the logs when the server starts running if possible? Also which Java version are you running on Heroku?

**Comment by dangmai** [comment]
I've added support for this in `master`, it will be included in the next release. When you call `start-apex-server`, you can now specify `--host` and `--port` for your purpose.

Thanks for raising this issue!
