### ISSUE TITLE
Lines with long class names do not respect print width

### ISSUE THREAD

**Issue by ryemcc** [dangmai/prettier-plugin-apex#493]
**Input:**

```apex
SomePrettyLongClassName.SomeSubclassNameLongToo descriptiveName =
    (SomePrettyLongClassName.SomeSubclassNameLongToo)
        JSON.deserialize(requestJSON,
            SomePrettyLongClassName.SomeSubclassNameLongToo.class);
```

**Actual output:**

```apex
SomePrettyLongClassName.SomeSubclassNameLongToo descriptiveName = (SomePrettyLongClassName.SomeSubclassNameLongToo) JSON.deserialize(
        requestJSON,
        SomePrettyLongClassName.SomeSubclassNameLongToo descriptiveName.class
      );
```

**Expected output:**

```apex
SomePrettyLongClassName.SomeSubclassNameLongToo descriptiveName =
    (SomePrettyLongClassName.SomeSubclassNameLongToo)
        JSON.deserialize(requestJSON,
            SomePrettyLongClassName.SomeSubclassNameLongToo.class);
```
Expected output would be something like the above or something that breaks the line up so that it respects the print width setting. I've tried adjusting the print width to 80/100/120 to see what happens with the same result.

**Comment by dangmai** [comment]
Hi, thanks for the report. It's been a while since I looked at the formatting for assignment expression, so I need to look into the code to understand why it's like this in the first place. My guess is that it's the way in order to make other formatting choices easier, but I could be wrong.

In general though, the print width is only a guide on where to break, not a hard rule. This is the case for Prettier core as well - for example if you have a variable name that exceeds the print width it's not like we can break it up.

For this particular instance I'll have to do my research to see if breaking the expression up is the right thing to do by comparing it to Prettier does to other core languages, as well as checking if doing that will bring on too much of maintenance in the future.

**Comment by ryemcc** [comment]
Thanks very much for looking into it. That makes total sense about the print width being a guide, not a rule. Just to be clear, the main issue for me here isn't that the plugin doesn't break up the lines automatically (though that would be nice!), but that the plugin "corrects" an input **with** line breaks into an output **without** them.

**Comment by dangmai** [comment]
Ah I see what you mean. So in general the prettier algorithm doesn't take into account the original input formatting, although there are certain exceptions to that. Basically what the algorithm does is map an Abstract Syntax Tree for the input (which doesn't contain information about the original formatting) into one stable output.

For this instance I do see the merit of your expected output, it's just a matter of seeing whether that can be achieved in a stable and maintainable manner.

**Comment by dangmai** [comment]
So I have looked into this, and unfortunately tweaking the formatting to be closer to your expected output leads to a lot of changes in other parts of the code base, and more tough formatting decisions down the road. The current formatting is also in line with how upstream Prettier handles Javascript code - see [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHATnGMCeAZaAcwDUBDdAS1ICMAbOAOVIFs4A6ANznXyIAV0EVN1xNWAAgC8AHSjjxAKQDKAeQZsAJnADO3KrQoAvOAApZ86TEwBHAK46YytQBpz4y0oisBWXASiEAMK0pNraYuyerEq21GAhYRH+hAAqEBBs8aHabgCUANwgziBCMBTQ2sig5IIA7nzkCJUopLS1pDiVxdTopGAA1lhKLHB4FFBwyABmrbrdvQNDqH3jhMhW9sVwzNRwGloaeKQBtqSEcABiEOjMpNiryCCktjAQRSAAFjDMtADqHxR4NplmA4EomoCKBxAThHmAwu9xrp0DABGdbtNZnBigArbQADyUq3oAEVbBB4JjaHM0ORkY9qDQ4LR3hhxjBfhQNDAPsgABwABmKGAgul+vVQjwwOm4XHedgpcAEQmaT20AFoJns9u8bLYKJg0YQMUgZtTsSBdMwKOt0JtLcS4GTFVSaTAaJzubykAAmYpWUgUAwBQJeE0gHQAVnetl0KRozTNNI49gAklAtLAlGBKKgYABBDNKXD0V1wAC+5aAA) for example, and one of my goals for this library is to align with upstream, so that developers don't encounter different behaviors when formatting Apex vs LWC/Aura.

I'd say this is one of those cases where usage of `// prettier-ignore` is completely warranted if the output doesn't match with how you expect it to look. IMO long expressions are always tough to format in a way that satisfies everyone, so I'd rather stick to a consistent formatting instead.

Hope you understand the decision, and thanks for raising the issue in the first place.
