### ISSUE TITLE
Japanese doc comments are garbled

### ISSUE THREAD

**Issue by takahitomiyamoto** [dangmai/prettier-plugin-apex#54]
We often use Japanese in doc comment, but prettier-plugin-apex does not seem to support Japanese. Please support Japanese or advise to me how to fix this issue. 

For example:
```apex
public with sharing class Demo {
  // 名前
  private String name;
}
```
By using prettier-plugin-apex, this code has been formatted as follows:
```apex
public with sharing class Demo
 { // 名前
  private String name;
}
```

In other example, this code
```apex
public with sharing class Demo {
  // Name
  private String name;

  // セッター
  public void setName(String name) {
    this.name = this.name;
  }
}
```
has been formatted as follows:
```apex
public with sharing class Demo {
  // Name
  private String name

  ; // セ�?ター

  public void setName(String name) {
    this.name = this.name;
  }
}
```

Best regards,
Takahito

**Comment by dangmai** [comment]
Thank you for the bug report! I actually did a lot of work yesterday to support Unicode, and this should be fixed now. It will be available in the next release (my guess is that it will come out some time this week). I did include your samples in the test suite so that we won't face this issue again in the future.

**Comment by dangmai** [comment]
Hey FYI I've just released the new version that contains the fix for this.

**Comment by takahitomiyamoto** [comment]
@dangmai Thank you so much! resolved!!
