### ISSUE TITLE
Empty classes are formatted over multiple lines

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#558]
This is perhaps more of a preference thing, but if using Prettier for JS as the model, Prettier would put an empty class all on one line. The newline here feels a little out of place since the class has no members. Thoughts?

I know you have a lot going on (cool that you're re-writing the library in TS!), but I figure this one may be low-hanging fruit if you agree with the formatting change.

Thanks again!

**Input:**

```apex
public class CustomException extends Exception {}
```

**Actual output:**
```apex
public class CustomException extends Exception {
}
```

**Expected output:**

```apex
public class CustomException extends Exception {}
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu] Windows 10
- Version: [e.g. 1.0.0] 1.10.0

**Comment by dangmai** [comment]
Hey there, thank you for raising this issue. This is actually a deliberate choice that was made back when this project first started. Please see https://github.com/dangmai/prettier-plugin-apex/issues/15

This is definitely one of the cases where I make different choices than core Prettier. It would take quite a bit of convincing for me to change this behavior, because it is tied to quite a few other formatting decisions (especially with regards to comment handling).

**Comment by no-stack-dub-sack** [comment]
Got it, makes sense. Thanks for clarifying!
