### ISSUE TITLE
Do not move NOPMD comments from the start of Block SOQL Expressions

### ISSUE THREAD

**Issue by williambritt** [dangmai/prettier-plugin-apex#597]
## Business Case
As a developer on the Salesforce platform, I would like to be able to automatically leverage code formatting tools as well as static analysis tools to ensure my code has standardized formatting as well as being secure.

Salesforce has identified prettier-plugin-apex as a possible solution for formatting Apex and PMD as a solution for static code analysis.

## Issue

When using Prettier for formatting and PMD for static code analysis, if a SOQL CRUD check violation is suppressed using a NOPMD comment, Prettier moves the NOPMD comment within the Block SOQL statements from the line with the `[` to the next line causing the PMD suppression to no longer be on the same line. This results in the SOQL violation that was originally suppressed no longer being suppressed as the empty line with the NOPMD comment is now the line being suppressed.

This issue is not a **direct** issue with Prettier or PMD individually, however, this behavior causes a lack of interoperability with the two tools suggested by Salesforce. Currently in order to solve this, one must either use a `// prettier-ignore` ignore comment or the PMD `SuppressWarning` annotation. Both of these actions bypass this issue by inhibiting the tools usage on that code block.
Here is additional information regarding PMD Suppressions: https://pmd.github.io/pmd-6.47.0/pmd_userdocs_suppressing_warnings.html

### Example
**Input:**

``` java
void PMDSOQL(){

  List<Account> a1 = [ // NOPMD - my PMD Suppression comment
    SELECT Id, field1, field2, field3, field4, field5 FROM Account];
}
```
**Actual output:**

``` java
void PMDSOQL() {
  List<Account> a1 = [ 
    // NOPMD - my PMD Suppression comment
    SELECT Id, field1, field2, field3, field4, field5
    FROM Account
  ];
}
```

**Expected output:**

``` java
void PMDSOQL() {
  List<Account> a1 = [ // NOPMD - my PMD Suppression comment
    SELECT Id, field1, field2, field3, field4, field5
    FROM Account
  ];
}
```

### Example Solution: Modify the handleSoqlExpression method within printer.ts
[printer.ts handleSoqlExpression](https://github.com/dangmai/prettier-plugin-apex/blob/57918b7a7abff43d4c788ee88f2dae8cec84ace7/src/printer.ts#L1880)

Due to this issue only affecting Block SOQL statements we can limit this changes to the formatting of `apex.jorje.data.ast.Expr$SoqlExpr` nodes instead of trying to treat every NOPMD comment differently from regular comments which would vastly increase the scope of the requested change. Additionally, I am not aware of another instance where the NOPMD comment is being moved, thus doing a broader solution potentially wouldn't be providing any gain, but would increase the scope.

It seems the two instances where the `apex.jorje.data.ast.Expr$SoqlExpr` formatting is leveraged is during direct block SOQL as well as within the For Loop Control expression. This should not impact inner queries as actual formatting of the SOQL syntax (contents within the brackets/parentheses) are within the `apex.jorje.data.soql.Query` nodes and the inner for loop formatting handles the parentheses before calling the `apex.jorje.data.soql.Query` formatting.

A solution is to modify the `handleSoqlExpression` method to evaluate the formatted output of the Query nodes to determine if the first item is a NOPMD comment. 

Here is what that change could look like:
``` typescript
function handleSoqlExpression(path: AstPath, print: printFn): Doc {
  const parts: Doc[] = [];
  parts.push("[");
  const tempParts: Doc = path.call(print, "query");
  const genericTempParts: any = tempParts;

  // Determine if next item after the opening bracket was a NOPMD comment
  const nextItemIsPMDComment =
    typeof genericTempParts?.[0]?.[0]?.[0] === "string" &&
    genericTempParts[0][0][0].includes("NOPMD");

  if (nextItemIsPMDComment) {
    parts.push(" ");
  } else {
    parts.push(softline);
  }
  parts.push(tempParts);
  parts.push(dedent(softline));
  parts.push("]");
  return groupIndentConcat(parts);
}
```

#### Other options evaluated but results in other styling changes:
- Use `line` instead of softline: This causes an extra space to be in all queries. 
- Move the `softline` into the `handleQuery` however the NOPMD comment is added by Prettier after the `handleQuery` invocation so `handleQuery` cannot handle this condition.

**Additional information (please fill this out)**:

- OS: Mac
- Version: 1.8.0 & Master branch

**Comment by dangmai** [comment]
Hi, thank you for the very detailed report. I will have to take a look at this and see if it's feasible - the issue with comments is that it's very difficult to make their formatting stable, so things that look easy are usually not. 

One thing I did notice is that `NOPMD` is just a convention and the user can change it with `-suppressmarker` in PMD, so that will make the implementation for this more difficult.

I'm trying to think of workarounds that can help in the meantime, does PMD recognize block comment for NOPMD (i.e. `/* NOPMD */`) instead of line comments? If it does, you can do something like this instead:

```
/* NOPMD */List<Account> a1 = [
    SELECT Id, field1, field2, field3, field4, field5 FROM Account];
```

**Comment by dangmai** [comment]
Yeah that's what I'm thinking as well, and actually I believe I already made that chance in some feature branch on my local repository to handle some other edge cases, so hopefully it's a two birds one stone situation here.

I'll keep this ticket open for now, and hopefully can come up with some fix for it in the future.

**Comment by dangmai** [comment]
So unfortunately I don't think it is feasible to make this change. I did take a long look into this, and changing how the comment is formatted spirals into a lot of unexpected changes that I have to handle, and at this point the cost of chasing down all these changes outweighs the benefits for me.

Another thing that weighs into my decision is that this change is not confined to just SOQL/SOSL queries. You can make the same case for any type of Block Statements like this as well:

```apex
private void main() { // NOPMD

}}
```

or

```apex
if (someCondition == true) { // NOPMD
}
```

Which means that if I make this change, I will eventually have to make changes to other cases (or the formatting won't be consistent).

Yet another reason is that the current behavior is consistent with how Prettier upstream formats Javascript (and other languages), and changing it means inconsistent behavior between Prettier Apex vs Prettier JS (which users most likely use for LWC development as well).

With that said, I do recognize that this is a pain for people using both Prettier Apex and PMD (me included). I can think of a few ways to work around this issue:

- Using `@SuppressWarnings('PMD')` annotation instead of `// NOPMD` marker. This works in some cases and not others, because annotations are only acceptable in certain context, but it can be a workaround. For example, you can refactor the queries that need these suppressions into a class/method, and apply the annotation to that class/method.

- Ask the PMD project to accept suppress marker in block comments in addition to end of line comments. If that can be done, then the workaround I proposed in my [earlier comment](https://github.com/dangmai/prettier-plugin-apex/issues/597#issuecomment-1187426025) will work. Looking at their code base, I don't see why they can't support this - https://github.com/pmd/pmd/blob/bdbeef6235fc6871f7e814f5f5d821a7be9fd34a/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L422 specifically checks for EOL comments, and it's probably worth a try to accept block comments as well.

I am closing this ticket because I don't foresee myself making this change. If somebody wants to open PR that addresses the issues mentioned above and is somewhat maintainable, I'd be happy to take a look.
