### ISSUE TITLE
DML Keywords are formatted to lowercase

### ISSUE THREAD

**Issue by chetanj257** [dangmai/prettier-plugin-apex#635]
DML Keywords are formatted to lowercase.
Eg:
`INSERT contactRecords;` -> will be formatted as `insert contactRecords;`
`UPDATE contactRecords;` -> will be formatted as `update contactRecords;`

If I have used uppercase explicitly. shouldn't it leave as is?

**Comment by dangmai** [comment]
Hi, thank you for opening the ticket. I can see where you are coming from, but I don't see this as an issue. `insert` and `update` are normal Apex keywords, and my opinion is that all normal Apex keywords should be formatted in lowercase. If we look at a different Apex keyword (`for`) for example:

```apex
FOR (Integer a = 0; a < 1; a++) {
}
```

The library will format it as:

```apex
for (Integer a = 0; a < 1; a++) {
}
```
`insert` and `update` are no different.

I'm closing this issue because I don't foresee changing this behavior in the future.
