### ISSUE TITLE
Fails to format ignored if/else with comments

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#688]
Hey @dangmai, thanks for getting the latest release out! 

So, the reasoning for #464 was to break up complex conditionals, and sometimes in this case, its nice to be able to add a comment about what's going on. E.g.

**Input:**

```apex
// a comment about this condition
if (foo) {
  // do something
}

// a comment about this condition
// prettier-ignore
else if (bar) {
  // do something else
}

// a comment about the catch-all
// prettier-ignore
else {
  // do the last thing
}
```

**Actual output:**

Error!
```sh
["ERROR" - 4:56:19 PM] Error formatting document.
["ERROR" - 4:56:19 PM] Comment "// a comment about this condition" was not printed. Please report this error!
Error: Comment "// a comment about this condition" was not printed. Please report this error!
	at Object.ensureAllCommentsPrinted (c:\Users\pweinberg\Code\Projects\l2c-user-assignment\node_modules\prettier\index.js:13357:13)
	at coreFormat (c:\Users\...\node_modules\prettier\index.js:14057:14)
	at formatWithCursor$1 (c:\Users\...\node_modules\prettier\index.js:14284:14)
	at (c:\Users\...\node_modules\prettier\index.js:59304:12
	at Object.format (c:\Users\...\node_modules\prettier\index.js:59324:12)
	at t.default.format (c:\Users\pweinberg\.vscode\extensions\esbenp.prettier-vscode-9.9.0\dist\extension.js:1:14565)
	at async t.PrettierEditProvider.provideEdits (c:\Users\pweinberg\.vscode\extensions\esbenp.prettier-vscode-9.9.0\dist\extension.js:1:11259)
	at async F.provideDocumentFormattingEdits (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:45332)
```

**Expected output:**
Same as input

I was actually thinking some more about this, and what about instead of having to use `prettier-ignore`, conditionals broken up by comments just didn't fold up? This is how JavaScript prettier behaves these days as well. E.g. this could just be left as-is, without the need to ignore anything:

```apex
// a comment about this condition
if (foo) {
  // do something
}

// a comment about this condition
else if (bar) {
  // do something else
}

// a comment about the catch-all
else {
  // do the last thing
}
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Plugin Version: 1.11.0

**Comment by dangmai** [comment]
Hi, thanks for this bug report!

I think your expected output is reasonable, however it might not be easy to achieve, because of how difficult it is to make comment formatting stable. I'm in the middle of making changes to comment formatting anyway, so I will try to see if it is feasible to format comments like that.

The issue with comment not getting printed is 100% a bug though, I will fix that for sure.

**Comment by no-stack-dub-sack** [comment]
Excellent - thanks for being such an attentive maintainer of this lib!

**Comment by dangmai** [comment]
This has been fixed in `master` and will be included in the next release. It turns out to be much bigger than I anticipated. The new behavior follows your expected output (in which comments in-between If-Else and Try-Catch blocks are kept in the original position instead of being pulled into the blocks themselves).

**Comment by no-stack-dub-sack** [comment]
Awesome! Saw the release just went out. Will be giving this a try shortly. Thanks as always for your efforts here.
