### ISSUE TITLE
Github Actions Example?

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#718]
@dangmai Do you by any chance have an example of the plugin being used in the context of a github actions workflow? Would the pre-requisite simply be to ensure Java and Node are installed? I've seen your CI example [here](https://github.com/dangmai/prettier-plugin-apex#continuous-integration), but wondering how this translates to GH actions, specifically if `runs-on` is set to `windows-latest`. Also, is there any chance you can break down `>dev/null 2>&1 &`? It's a bit hard to search for chars like these on Google and I'm not all that familiar with these commands. 

Thanks in advance. No worries if you're busy!

**Comment by dangmai** [comment]
Hello,

I'm not planning on publishing a guide on Github Actions specifically. I do have a [section on the README](https://github.com/dangmai/prettier-plugin-apex#continuous-integration) for general CI/CD set up that can be applied to any CI/CD provider. IMO documentation needs to be upkept just like code, and I don't want to take that on. You can probably ping a dev advocate at Salesforce like @pozil for an official guide.

For your specific question, `>/dev/null 2>&1` means that we're redirecting the stdin and stderr to "nothingness". This is because we don't care about the output of the program. You keep remove that part if you do care about the output. The `&` means that the script will run in the background and allow us to run other commands simultaneously. Without it, the script will block other scripts from running. Unfortunately I am not versed enough in Windows scripting to know what the equivalent commands are for Powershell/CMD.

**Comment by no-stack-dub-sack** [comment]
Thanks for the explanation @dangmai. Maybe I'll look at some SF projects and see if they're already using the plugin in any of their workflows.

**Comment by no-stack-dub-sack** [comment]
@dangmai Found this in one of Salesforce's repos: https://github.com/trailheadapps/apex-recipes/blob/main/.github/workflows/ci-pr.yml

I suppose providing a link in the README has the same issue - if they don't keep it current it may get stale. but thought I'd add it here in case anyone else comes across this and finds it valuable.
