### ISSUE TITLE
Extra level indentation added in multi line string concatenation

### ISSUE THREAD

**Issue by pozil** [dangmai/prettier-plugin-apex#741]
Hi @dangmai, when upgrading from `1.11.0` to `1.12.0` I noticed that the plugin is adding an extra level indentation when running in multi line string concatenation.
I don't think that this is the desired output, this feels more like an undesired side effect of fixing https://github.com/dangmai/prettier-plugin-apex/issues/693.

**Input:**

```apex
InvalidParameterValueException e = new InvalidParameterValueException(
    'fieldName',
    fieldName
);
e.setMessage(
    'Could not find field ' +
    fieldName +
    ' on object ' +
    objectName
);
```

**Actual output:**

Undesired indentation on line 7-9 (message parts should be on same indentation level):

```apex
InvalidParameterValueException e = new InvalidParameterValueException(
    'fieldName',
    fieldName
);
e.setMessage(
    'Could not find field ' +
        fieldName +
        ' on object ' +
        objectName
);
```

**Expected output:**

```apex
InvalidParameterValueException e = new InvalidParameterValueException(
    'fieldName',
    fieldName
);
e.setMessage(
    'Could not find field ' +
    fieldName +
    ' on object ' +
    objectName
);
```

**Additional information (please fill this out)**:

- OS: macOS Ventura
- Version: 1.12.0

**Comment by dangmai** [comment]
Hello, sorry for my late response, and thanks for opening this issue.

This is actually not an unintended consequence of the fix you mentioned, but an intended formatting change for binary-ish expressions going forward. The old behavior, albeit looking arguably better, makes it impossible for me to do indentation correctly in tricky formatting situations (such as #693).

Another big factor for me to switch to the new behavior is that it's how Prettier upstream formats Javascript, as you can see in this example [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcB0BnOMCycMYCGA5nABQA6UABNQOQDCEArgDYAm1UEM1AZgEsonOtQDUVWoLgcAcoQC2ccZPrVo6gEYArOGF6iJNLbv3ylK44W4wAFnABOAeR16Y55UdoBPbAEEbe2dXM0U4KgBKAG4QABoQCAAHGAFoDGRQQgcHCAB3AAUshHSUQlZcwm90+M0HQjAAa2wAZTCAGSE4ZD4yrBq6xpbE+qFiZBgHZjh4uAVNOHZ2BbbrYmYSOAAxCAcFQhgUqDHS5hgIOJBbGAVWAHVbAXgMYbA4ZuLHgQA3R+9kcAIFyEWAcMHydWIe26vWmIG0GAAHs1Rqw4ABFZg8LpIHqsPogYYOEH-TSEeasC6JBxCGC3ATsOzIAAcAAZ4lSIFhbnVEv8qfhHF8uvEAI6Y+DgpIlECEDAAWigcAWCwuDjgYoEavBJChOJh8SwCgE40msIwKLgfgO1M0pzg+UcHUV0LxZotGKxLvxMDJdIZtmQACZ4hNCAJWKMmApdagMABWC7MLAAFTJJVx+K+UwAksIEDBmmBqckAuxmjBvKivXAAL41oA). This makes it so that LWC Javascript code formatted by Prettier and Apex code formatted by this plugin will have similar behavior going forward.

Maybe I should've phrased the CHANGELOG a bit better so that it's clear the fix is not just for a ticket, but a bigger change overall 😅
