### ISSUE TITLE
Option for opening brace

### ISSUE THREAD

**Issue by jairzh** [dangmai/prettier-plugin-apex#82]
Is there an option like [prettier/plugin-php](https://github.com/prettier/plugin-php) to format  brace as a new line?

More discussion to check this issue - [prettier/plugin-php - Option for opening brace](https://github.com/prettier/plugin-php/issues/107)

**Comment by dangmai** [comment]
Hey, thank you for the issue report. I am sympathetic to the new line brace style and I do know that some code bases currently use that style. However, I'm not planning on adding that option for a few reasons:

- The biggest issue is that adding options create exponentially more surface areas for me to test/develop for. This plugin is already big enough, since it is actually 3 languages in 1 plugin (Apex, SOQL, SOSL).
- Prettier core does not support that option - I believe the PHP plugin might be the only one that supports it.
- This is meant to be a very opinionated formatter, so that teams can stop debating about code styles. The more options we add, the less impactful that decision is.
