### ISSUE TITLE
For loop spacing before colon

### ISSUE THREAD

**Issue by codermpl** [dangmai/prettier-plugin-apex#86]
All the Salesforce documentation I have seen includes a space in a for loop on both sides of the colon (:). however, prettier-plugin-apex seems to be removing the space before the colon. See https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_loops_for_lists.htm

Example: for (Integer i : myInts) to for (Integer i: myInts)

**Comment by dangmai** [comment]
Thank you for the report! You're right that Salesforce doc does put a space before the colon. It's a style that I don't personally use, but it does make logical sense because other operators have spaces before them (e.g. `a = 1`).

I will most likely make a fix for this, even though I don't like it haha.

**Comment by dangmai** [comment]
I've made a fix for this in the `master` branch and will push out a new version soon.

**Comment by dangmai** [comment]
`1.0.0-rc.5` has been published and contains a fix for this.
