### ISSUE TITLE
Is there an option to add a space between the method name and its signature?

### ISSUE THREAD

**Issue by renatoliveira** [dangmai/prettier-plugin-apex#89]
Is there an option to add a space between the method name and its signature?

To format, for example:

```apex
public String returnName(Contact c) { ...
```

to

```apex
// notice the space between the method's name and `(Contact c)`
public String returnName (Contact c) { ...
```

**Comment by dangmai** [comment]
Thank you for the issue report. I do know that some code bases currently use that style and I can kinda see why. However, there is currently no option for it and I'm not planning on adding that option for a few reasons:

- The biggest issue is that adding options create exponentially more surface areas for me to test/develop for. This plugin is already big enough, since it is actually 3 languages in 1 plugin (Apex, SOQL, SOSL).
- Prettier core does not support that option.
- This is meant to be a very opinionated formatter, so that teams can stop debating about code styles. The more options we add, the less impactful that decision is. Prettier even has a dedicated page on the rationale behind this [here](https://prettier.io/docs/en/option-philosophy.html).
