### ISSUE TITLE
Spaces are missing in curly braces

### ISSUE THREAD

**Issue by garychenming** [dangmai/prettier-plugin-apex#99]
```sh
# Prettier options (if any):
```

**Input:**

```apex
// code snippet
Map<Id, SObject> accountMapping = new Map<Id, SObject>{ accountId => Account }; 
```

**Actual output:**

```apex
// code snippet
Map<Id, SObject> accountMapping = new Map<Id, SObject>{accountId => Account}; 
```

**Expected output:**

```apex
// code snippet

Map<Id, SObject> accountMapping = new Map<Id, SObject>{ accountId => Account };
```

**Additional information (please fill this out)**:

- OS: [OS X]
- Version: [10.14.5]

**Comment by dangmai** [comment]
Hi, thank you for the report! To be honest this is one of the cases where I'm still not sure what the right decision is, since adding a space makes it inconsistent with other rules like: no spacing between parentheses - `a.callMethod(b, c);`, no space between square brackets - `a[0]`, etc.

I'm going to do more thinking about this and will make a decision about it soon. I know the Prettier project regrets having an option for this, so I'd prefer us making a decision about it instead of having an option.

**Comment by dangmai** [comment]
OK I've made a decision about this, I'll add the spaces in but will not include the option to disable that behavior. This is so that it's consistent with the default behavior of Prettier JS, but also side step the configuration rabbit hole.

**Comment by garychenming** [comment]
That would be great, thank you for your reply.
